CREATE TABLE T1_EXT1 (
    ID NUMBER(10),
    NAME VARCHAR2(50),
    DEPTNO NUMBER(2)
)
ORGANIZATION EXTERNAL (
    TYPE ORACLE_LOADER
    DEFAULT DIRECTORY EXTERNAL_DIR
    ACCESS PARAMETERS (
        RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY ","
        (
            ID,
            NAME,
            DEPTNO
        )
    )
    LOCATION (EXTERNAL_DIR:'t1_data.csv')
)
REJECT LIMIT UNLIMITED;
