create table AAAAAAAAA.BBBBBBBBBBBBBBBBBB
(
  id                       NUMBER,
  xys_sbxno                 VARCHAR2(50),
  xys_sbxno              VARCHAR2(50),
  xys_sbxvin                  VARCHAR2(50),
  xys_sbxmanufacturer         VARCHAR2(64),
  xys_sbxid                 VARCHAR2(40),
  xys_sbxname               VARCHAR2(128),
  xys_sbxid                 VARCHAR2(40),
  xys_sbxname               VARCHAR2(128),
  xys_sbxid                 VARCHAR2(64),
  xys_sbxname               VARCHAR2(256),
  xys_sbxprice              NUMBER,
  xys_sbxprice               NUMBER,
  xys_sbxclass           VARCHAR2(64),
  xys_sbxtype                VARCHAR2(64),
  xys_sbxno                VARCHAR2(200),
  xys_sbxcolor                VARCHAR2(40),
  xys_sbxdate        DATE,
  xys_sbxdate          DATE,
  xys_sbxby                VARCHAR2(50),
  xys_sbxtime              DATE,
  xys_sbxby                VARCHAR2(50),
  xys_sbxtime              DATE,
  xys_sbxflag                 CHAR(1),
  xys_sbxinternet              VARCHAR2(2),
  xys_sbxgreen                 VARCHAR2(64),
  xys_sbxnum                 NUMBER,
  configure                VARCHAR2(200),
  xys_sbxstyle               VARCHAR2(20),
  driver                   VARCHAR2(80),
  blowoff                  VARCHAR2(64),
  xys_sbxmain            VARCHAR2(80),
  xys_sbxdetail          VARCHAR2(80),
  xys_sbxtime             DATE,
  xys_sbxage              VARCHAR2(20),
  version                  NUMBER,
  xys_sbxbusiness         VARCHAR2(10),
  xys_sbxnum            VARCHAR2(80),
  xys_sbxcertified             VARCHAR2(20),
  xys_sbxprice          NUMBER,
  xys_sbxtime             DATE,
  wight                    NUMBER,
  xys_sbxflag              VARCHAR2(20),
  xys_sbxtype             VARCHAR2(40),
  xys_sbxparallel              VARCHAR2(20),
  xys_sbxstatus         VARCHAR2(20),
  xys_sbxlength               NUMBER,
  xys_sbxbase               NUMBER,
  xys_sbxvin              VARCHAR2(50),
  engine                   VARCHAR2(200),
  xys_sbxdrive         VARCHAR2(200),
  xys_sbxlength         NUMBER,
  xys_sbxform           VARCHAR2(200),
  xys_sbxmodel             VARCHAR2(200)
)
organization external
(
  type ORACLE_LOADER
  default directory EXTERNAL_NEW_SP
  access parameters 
  (
    records delimited by newline
    characterset UTF8
    nobadfile
    nodiscardfile
    nologfile
    fields terminated by '<>'
    MISSING FIELD VALUES ARE NULL
    (
       id  ,
  xys_sbxno  ,
  xys_sbxno   ,
  xys_sbxvin,
  xys_sbxmanufacturer  ,
  xys_sbxId  ,
  xys_sbxname,
  xys_sbxid   ,
  xys_sbxname   ,
  xys_sbxid    ,
  xys_sbxname ,
  xys_sbxprice   ,
  xys_sbxpassenger,
       mileage   ,
  xys_sbxprice ,
  xys_sbxbelongs ,
  xys_sbxno   ,
  xys_sbxaddress,
  xys_sbxplate  ,
  xys_sbxappraiser  ,
  xys_sbxprice   ,
  xys_sbx CHAR (19) DATE_FORMAT DATE MASK "YYYY-MM-DD HH24:MI:SS",
  xys_sbx CHAR (19) DATE_FORMAT DATE MASK "YYYY-MM-DD HH24:MI:SS",
  xys_sbxlicense   ,
  xys_sbxprovince    ,
  xys_sbxcity    ,
  xys_sbxaddress   ,
  xys_sbxid    ,
  xys_sbxid  ,
  xys_sbxname   ,
  xys_sbxphone    ,
  xys_sbxprovince  ,
  xys_sbxcity   ,
  xys_sbxcounty   ,
  xys_sbxstreet    ,
  xys_sbxaddress    ,
  xys_sbxprovince   ,
  xys_sbxcity    ,
  xys_sbxnum ,
  xys_sbxnums  ,
  xys_sbxtrans   ,
  xys_sbxmortgage   ,
  xys_sbxnum  ,
  xys_sbxkind   ,
  xys_sbxuse    ,
  xys_sbx CHAR (19) DATE_FORMAT DATE MASK "YYYY-MM-DD HH24:MI:SS" ,
  xys_sbx CHAR (19) DATE_FORMAT DATE MASK "YYYY-MM-DD HH24:MI:SS",
  xys_sbx CHAR (19) DATE_FORMAT DATE MASK "YYYY-MM-DD HH24:MI:SS" ,
  xys_sbxby   ,
  xys_sbx CHAR (19) DATE_FORMAT DATE MASK "YYYY-MM-DD HH24:MI:SS" ,
  xys_sbxby   ,
  xys_sbx CHAR (19) DATE_FORMAT DATE MASK "YYYY-MM-DD HH24:MI:SS" ,
  xys_sbxflag    ,
  xys_sbxmain   ,
  xys_sbxdetail    ,
  xys_sbx CHAR (19) DATE_FORMAT DATE MASK "YYYY-MM-DD HH24:MI:SS" ,
  xys_sbxage    ,
       version ,
  xys_sbxbusiness   ,
  xys_sbxnum   ,
  xys_sbxcertified    ,
  xys_sbxprice  ,
  xys_sbx CHAR (19) DATE_FORMAT DATE MASK "YYYY-MM-DD HH24:MI:SS" ,
       wight   ,
  xys_sbxflag  ,
  xys_sbxtype   ,
  xys_sbxparallel ,
  xys_sbxstatus   ,
  xys_sbxlength,
  xys_sbxtype   ,
  xys_sbxtype    ,
  xys_sbxphone    ,
  xys_sbxtype    ,
  xys_sbxplate    ,
  xys_sbxprovince   ,
  xys_sbxcity  ,
  xys_sbxdate   ,
  xys_sbxprovince
       )
  )
  location (EXTERNAL_NEW_SP:'APPLY_CAR_DETAILS.csv')
)
reject limit UNLIMITED;
